services:
  postgres:
    image: postgres
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    env_file:
      - .env 
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
