services:
  postgres:
    image: postgres
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    environment:
      POSTGRES_PASSWORD: "eurofarma123"
    ports:
      - "5432:5432"